config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :answers
  resources :piiza_ids
  resources :options
  resources :questions
  resources :punchlines
  resources :names
  resources :ingredients



  post 'generator/:salty/:sweet/:vegetarian' => 'ingredients#generator', :as => :pizza_generator
   get 'generator/:salty/:sweet/:vegetarian' => 'ingredients#generator'
  root 'ingredients#welcome'

  post 'quiz' => 'answers#quiz'
    get 'quiz' => 'answers#quiz' 
    get 'personality' => 'answers#personality'







end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base

has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]

  # GET /ingredients
  # GET /ingredients.json


#added new view
def generator
  if params[:salty] == "true"
    #we are selecting EVERYTHING except sweet
    @ingredients = Ingredient.where(:sweet => false)

  elsif params[:sweet] == "true"
    @ingredients = Ingredient.where(:sweet => true)

  elsif params[:vegetarian] == "true"
    @ingredients = Ingredient.where(:vegetarian => true)

  end

count = @ingredients.count 
if count > 0 
    random = Random.rand(count)
    @name1 = @ingredients [random].name    

    count = @ingredients.count
    random = Random.rand(count)
    @name2 = @ingredients[random].name

    count = @ingredients.count
    random = Random.rand(count)
    @name3 = @ingredients[random].name
    
   @names = Name.all 
    count = @names.count 
    if count > 0
    random = Random.rand(@names.count)
    @name = @names[random].name 
  else
    @name = "No cool name available"
end

  @punchlines = Punchline.all
  count = @punchlines.count
     if count > 0
    random = Random.rand(@punchlines.count)
    @punchline = @punchlines[random].name
  else
    @name = "No punchline here"
end

  else 
    @name1 = "No"
    @name2 ="Ingredients"
    @name3 = "Avaliable"
  end

end


def welcome
    @ingredients = Ingredient.all
  end

  def index
    @ingredients = Ingredient.all
  end

  # GET /ingredients/1
  # GET /ingredients/1.json
  def show
  end

  # GET /ingredients/new
  def new
    @ingredient = Ingredient.new
  end

  # GET /ingredients/1/edit
  def edit
  end

  # POST /ingredients
  # POST /ingredients.json
  def create
    @ingredient = Ingredient.new(ingredient_params)

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully created.' }
        format.json { render :show, status: :created, location: @ingredient }
      else
        format.html { render :new }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingredients/1
  # PATCH/PUT /ingredients/1.json
  def update
    respond_to do |format|
      if @ingredient.update(ingredient_params)
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully updated.' }
        format.json { render :show, status: :ok, location: @ingredient }
      else
        format.html { render :edit }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    @ingredient.destroy
    respond_to do |format|
      format.html { redirect_to ingredients_url, notice: 'Ingredient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ingredient_params
      params.require(:ingredient).permit(:vegetarian, :salty, :sweet, :name, :avatar)
    end
end


app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/ingredients/_form.html.erb
<%= form_for(@ingredient, html: { multipart: true }) do |f| %>
  <% if @ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
      <% @ingredient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= f.file_field :avatar %>



 <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :vegetarian %><br>
    <%= f.check_box :vegetarian %>
  </div>
  <div class="field">
    <%= f.label :salty %><br>
    <%= f.check_box :salty %>
  </div>
  <div class="field">
    <%= f.label :sweet %><br>
    <%= f.check_box :sweet %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ingredients/edit.html.erb
<h1>Editing Ingredient</h1>

<%= render 'form' %>

<%= link_to 'Show', @ingredient %> |
<%= link_to 'Back', ingredients_path %>

app/views/ingredients/generator.html.erb
<body id="background1">
<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Raleway" />


<center>
	<h1 class="header" style="padding: 70px 10px 10px 10px">Your dream pizza is...</h1>

<br>
<br>
<br>
<br>

<div id="block">
<div id="container1">

 <p class="body1">

<%= @name1%> |
<%= @name2%> |
<%= @name3%> 

<br>

<h class="h2">
<%= @name%>
<%= @name2%>
<%= @punchline%>
</h>
</div>
</div>
</p> 


</center>


</body>

app/views/ingredients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ingredients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Vegetarian</th>
      <th>Salty</th>
      <th>Sweet</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ingredients.each do |ingredient| %>
      <tr>
        <td><%= ingredient.name %></td>

        <% if ingredient.vegetarian %>
          <td>Yes</td>
          <% else%>
            <td> </td>
          <% end %>

        <% if ingredient.salty %>
          <td>Yes</td>
          <% else%>
            <td> </td>
          <% end %>

        <% if ingredient.sweet %>
        <td>Yes</td>
          <% else%>
            <td> </td>
          <% end %>

        <td><%= link_to 'Show', ingredient %></td>
        <td><%= link_to 'Edit', edit_ingredient_path(ingredient) %></td>
        <td><%= link_to 'Destroy', ingredient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ingredient', new_ingredient_path %>

app/views/ingredients/new.html.erb
<h1>New Ingredient</h1>

<%= render 'form' %>

<%= link_to 'Back', ingredients_path %>

app/views/ingredients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Vegetarian:</strong>
  <%= @ingredient.vegetarian %>
</p>

<p>
  <strong>Salty:</strong>
  <%= @ingredient.salty %>
</p>

<p>
  <strong>Sweet:</strong>
  <%= @ingredient.sweet %>
</p>

<!--this is code for an added gem on uploading images-->

<%= image_tag @ingredient.avatar.url %>
<%= image_tag @ingredient.avatar.url(:medium) %>
<%= image_tag @ingredient.avatar.url(:thumb) %>

<%= link_to 'Edit', edit_ingredient_path(@ingredient) %> |
<%= link_to 'Back', ingredients_path %>

app/views/ingredients/welcome.html.erb
<body id="background">

<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Raleway" />

<center>

<center>
	<h1 class="header" style="padding: 70px 10px 10px 10px">Random Pizza Generator</h1>


<br>
<br>
<br>
<br>
	    <div id="block">
		<div id="container">
		<p class="body">
			Choose your pizza style!
	    </p>
        </div>
        </div>

<br>
<br>


<div class="row">
	<table>

		<%= button_to "Vegetarian", pizza_generator_path(:vegetarian => :true, :salty =>:false, :sweet => :false), :class => "btn btn-default btn-lg", :role=>"group"%>

			<div class="divider">
				<br>
				<br>

		<%= button_to "Salty", pizza_generator_path(:vegetarian => :true, :salty =>:true, :sweet => :false), :class=>"btn btn-default btn-lg", :role=>"group"%>

			<div class="divider">
				<br>
				<br>

		<%= button_to "Sweet", pizza_generator_path(:vegetarian => :false, :salty =>:false, :sweet => :true), :class=>"btn btn-default btn-lg", :role=>"group"%>

	
 	</table>


 </div>

 <br>
<br>
<br>
<br>
	    <div id="block">
		<div id="container">
		<p class="body">
			Take our pizza personality test!
	    </p>
        </div>
        </div>


</body>



<!--this is an HTML FILE & comment-->
<!--underneath it this is a ruby code in HTML, also image link to image folder-->
<%#= image_tag "images/pic01.jpg" %>


