config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :answers
  resources :piiza_ids
  resources :options
  resources :questions
  resources :punchlines
  resources :names
  resources :ingredients



  post 'generator/:salty/:sweet/:vegetarian' => 'ingredients#generator', :as => :pizza_generator
   get 'generator/:salty/:sweet/:vegetarian' => 'ingredients#generator'
  root 'ingredients#welcome'

  post 'quiz' => 'answers#quiz'
    get 'quiz' => 'answers#quiz' 
    get 'personality' => 'answers#personality'







end

app/models/answer.rb
class Answer < ActiveRecord::Base
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
  end

def quiz 
  @options = []
  @questions = Question.all
  @questions.each do |question| 
  options = Option.where(:number=> question.id)
  @options << options
  end
end

def personality 
  @answer = Answer.where(:option1=>params[:option1], :option2=> params[:option2], :option3=>params[:option3]).first
  if !@answer.nil? 
  @piiza_id = @answer.piiza_id_id
  @pizza = PiizaId.where(:id => @piiza_id).first
  @name = @pizza.name
  @description = @pizza.description
  else
  @name = "have a salad"
  end 
end
  # GET /answers/new
 
  def new
    @answer = Answer.new
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(answer_params)

    respond_to do |format|
      if @answer.save
        format.html { redirect_to @answer, notice: 'Answer was successfully created.' }
        format.json { render :show, status: :created, location: @answer }
      else
        format.html { render :new }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to answers_url, notice: 'Answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:option1, :option2, :option3, :piiza_id_id)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.erb
<%= form_for(@answer) do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :option1 %><br>
    <%= f.text_field :option1 %>
  </div>
  <div class="field">
    <%= f.label :option2 %><br>
    <%= f.text_field :option2 %>
  </div>
  <div class="field">
    <%= f.label :option3 %><br>
    <%= f.text_field :option3 %>
  </div>
  <div class="field">
    <%= f.label :piiza_id_id %><br>
    <%= f.number_field :piiza_id_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing Answer</h1>

<%= render 'form' %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

app/views/answers/index.html.erb
<p id="notice"><%= notice %></p>


<h1>Listing Answers</h1>

<table>
  <thead>
    <tr>
      <th>Option1</th>
      <th>Option2</th>
      <th>Option3</th>
      <th>Piiza id</th>
      <th colspan="3"></th>
    </tr>
  </thead>


  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= answer.option1 %></td>
        <td><%= answer.option2 %></td>
        <td><%= answer.option3 %></td>
        <td><%= answer.piiza_id_id %></td>
        <td><%= link_to 'Show', answer %></td>
        <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
        <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Answer', new_answer_path %>

app/views/answers/new.html.erb
<h1>New Answer</h1>

<%= render 'form' %>

<%= link_to 'Back', answers_path %>

app/views/answers/personality.html.erb
<html>
<head>
   <title>Pizza Personality</title>
    <!-- You can use open graph tags to customize link previews.
    Learn more: https://developers.facebook.com/docs/sharing/webmasters -->
    <meta property="og:url"           content= "http://pizzagenerator.herokuapp.com/personality"/>
    <meta property="og:type"			content="article"/>
    <meta property="og:title"         content= "Pizza Personality"! />
    <meta property="og:image"         content="http://www.thickslicepizza.com/img/photo3.jpg" />
<body>

<body id="background1">
<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Raleway" />
<center>
	
	<h1 class="header" style="padding: 70px 10px 10px 10px">Your Pizza Personality is...</h1>
<br>
<br>
<br>
<br>
<div id="block">
<div id="containerquiz">

 <p class="h2">
<%= @name%>
</p>

 <p class="bodyquiz">
<%= @description%>
</p>

</div>
</div>

<div class="fb-share-button"  data-href="<%= request.original_url %>" data-layout="button_count"></div>

</center> 
</head>

app/views/answers/quiz.html.erb
<body id="backgroundquiz">

<center>
<%= form_tag("/personality", method:"get") do %>
<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Raleway" />




    <% @questions.each_with_index do |question,index| %>

<br>
	  <h1 class="header2" style="padding: 70px 10px 10px 10px"><%= question.name %></h1>
 
<br>

  	<% @options[index].each do |option| %><%= radio_button_tag "option"+(index+1).to_s, option.id, false,  {:class => "body", :style => "color: red"}%>
      <%= option.name %>


<%end%>
<% end%>    
<br>
<br>
<input class="btn btn-default" type="submit" value="Submit"></input>
<%end%>


</center>
</body>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Option1:</strong>
  <%= @answer.option1 %>
</p>

<p>
  <strong>Option2:</strong>
  <%= @answer.option2 %>
</p>

<p>
  <strong>Option3:</strong>
  <%= @answer.option3 %>
</p>

<p>
  <strong>Piiza id:</strong>
  <%= @answer.piiza_id_id %>
</p>

<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>