config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :answers
  resources :piiza_ids
  resources :options
  resources :questions
  resources :punchlines
  resources :names
  resources :ingredients



  post 'generator/:salty/:sweet/:vegetarian' => 'ingredients#generator', :as => :pizza_generator
   get 'generator/:salty/:sweet/:vegetarian' => 'ingredients#generator'
  root 'ingredients#welcome'

  post 'quiz' => 'answers#quiz'
    get 'quiz' => 'answers#quiz' 
    get 'personality' => 'answers#personality'







end

app/models/punchline.rb
class Punchline < ActiveRecord::Base
end

app/controllers/punchlines_controller.rb
class PunchlinesController < ApplicationController
  before_action :set_punchline, only: [:show, :edit, :update, :destroy]

  # GET /punchlines
  # GET /punchlines.json
  def index
    @punchlines = Punchline.all
  end

  def generator
  @punchlines = Punchline.all
  end 
  # GET /punchlines/1
  # GET /punchlines/1.json
  def show
  end

  # GET /punchlines/new
  def new
    @punchline = Punchline.new
  end

  # GET /punchlines/1/edit
  def edit
  end

  # POST /punchlines
  # POST /punchlines.json
  def create
    @punchline = Punchline.new(punchline_params)

    respond_to do |format|
      if @punchline.save
        format.html { redirect_to @punchline, notice: 'Punchline was successfully created.' }
        format.json { render :show, status: :created, location: @punchline }
      else
        format.html { render :new }
        format.json { render json: @punchline.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /punchlines/1
  # PATCH/PUT /punchlines/1.json
  def update
    respond_to do |format|
      if @punchline.update(punchline_params)
        format.html { redirect_to @punchline, notice: 'Punchline was successfully updated.' }
        format.json { render :show, status: :ok, location: @punchline }
      else
        format.html { render :edit }
        format.json { render json: @punchline.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /punchlines/1
  # DELETE /punchlines/1.json
  def destroy
    @punchline.destroy
    respond_to do |format|
      format.html { redirect_to punchlines_url, notice: 'Punchline was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_punchline
      @punchline = Punchline.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def punchline_params
      params.require(:punchline).permit(:name)
    end
end

app/helpers/punchlines_helper.rb
module PunchlinesHelper
end

app/views/punchlines/_form.html.erb
<%= form_for(@punchline) do |f| %>
  <% if @punchline.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@punchline.errors.count, "error") %> prohibited this punchline from being saved:</h2>

      <ul>
      <% @punchline.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/punchlines/edit.html.erb
<h1>Editing Punchline</h1>

<%= render 'form' %>

<%= link_to 'Show', @punchline %> |
<%= link_to 'Back', punchlines_path %>

app/views/punchlines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Punchlines</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @punchlines.each do |punchline| %>
      <tr>
        <td><%= punchline.name %></td>
        <td><%= link_to 'Show', punchline %></td>
        <td><%= link_to 'Edit', edit_punchline_path(punchline) %></td>
        <td><%= link_to 'Destroy', punchline, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Punchline', new_punchline_path %>

app/views/punchlines/new.html.erb
<h1>New Punchline</h1>

<%= render 'form' %>

<%= link_to 'Back', punchlines_path %>

app/views/punchlines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @punchline.name %>
</p>

<%= link_to 'Edit', edit_punchline_path(@punchline) %> |
<%= link_to 'Back', punchlines_path %>